
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 31 23:52:43 EST 2009
//----------------------------------------------------

module dflex.sym;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static immutable int DELIMITER = 9;
  public static immutable int EOFRULE = 26;
  public static immutable int STRING_I = 46;
  public static immutable int CHAR = 40;
  public static immutable int CONCAT = 45;
  public static immutable int MACROUSE = 42;
  public static immutable int LOWERCLASS = 25;
  public static immutable int EQUALS = 10;
  public static immutable int CCLASSNOT = 44;
  public static immutable int REPEAT = 32;
  public static immutable int TILDE = 39;
  public static immutable int CHAR_I = 47;
  public static immutable int STAR = 33;
  public static immutable int BAR = 35;
  public static immutable int FULL = 17;
  public static immutable int LOOKAHEAD = 28;
  public static immutable int LESSTHAN = 12;
  public static immutable int BANG = 38;
  public static immutable int COMMA = 11;
  public static immutable int JLETTERDIGITCLASS = 21;
  public static immutable int PLUS = 34;
  public static immutable int USERCODE = 31;
  public static immutable int EOF = 0;
  public static immutable int error = 1;
  public static immutable int DASH = 8;
  public static immutable int CLOSEBRACKET = 3;
  public static immutable int HAT = 4;
  public static immutable int JLETTERCLASS = 20;
  public static immutable int IDENT = 30;
  public static immutable int ACTION = 29;
  public static immutable int CLOSECLASS = 7;
  public static immutable int DIGITCLASS = 23;
  public static immutable int LBRACE = 14;
  public static immutable int REGEXPEND = 19;
  public static immutable int OPENCLASS = 6;
  public static immutable int OPENBRACKET = 2;
  public static immutable int POINT = 37;
  public static immutable int LETTERCLASS = 22;
  public static immutable int MORETHAN = 13;
  public static immutable int DOLLAR = 5;
  public static immutable int RBRACE = 15;
  public static immutable int STRING = 41;
  public static immutable int QUESTION = 36;
  public static immutable int UPPERCLASS = 24;
  public static immutable int NOACTION = 27;
  public static immutable int CCLASS = 43;
  public static immutable int ASCII = 16;
  public static immutable int UNICODE = 18;
}

